lista_preguntas = [
    {
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Quién es considerado el mejor jugador del mundo por muchos y campeón del mundo en 2022?",
        "respuesta_1": "Cristiano Ronaldo", 
        "respuesta_2": "Lionel Messi", 
        "respuesta_3": "Mbappé", 
        "respuesta_4": "Modric", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿En qué deporte se utiliza una pelota número 5?",
        "respuesta_1": "Vóley", 
        "respuesta_2": "Básquet", 
        "respuesta_3": "Fútbol", 
        "respuesta_4": "Handball", 
        "respuesta_correcta": 3},

    {   
        "categoria": "futbol",
        "dificultad": "facil",    
        "pregunta": "¿Cuántos jugadores tiene un equipo de fútbol dentro de la cancha?",
        "respuesta_1": "9", 
        "respuesta_2": "10", 
        "respuesta_3": "11", 
        "respuesta_4": "12", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Qué selección ganó la Copa del Mundo 2014?",
        "respuesta_1": "Argentina", 
        "respuesta_2": "Alemania", 
        "respuesta_3": "Brasil", 
        "respuesta_4": "España", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Cuál es el máximo torneo de clubes europeo?",
        "respuesta_1": "Europa League", 
        "respuesta_2": "Champions League", 
        "respuesta_3": "Conference League", 
        "respuesta_4": "Supercopa", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Qué país es famoso por el jugador Pelé?",
        "respuesta_1": "Argentina", 
        "respuesta_2": "Brasil", 
        "respuesta_3": "Chile", 
        "respuesta_4": "Uruguay", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Qué árbitro dirige un partido de fútbol?",
        "respuesta_1": "Director", 
        "respuesta_2": "Árbitro", 
        "respuesta_3": "Entrenador", 
        "respuesta_4": "DT", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Qué se saca tras cometer una falta dentro del área?",
        "respuesta_1": "Corner", 
        "respuesta_2": "Penal", 
        "respuesta_3": "Lateral", 
        "respuesta_4": "Saque de arco", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿Qué club es conocido como 'El Barca'?",
        "respuesta_1": "Real Madrid", 
        "respuesta_2": "Barcelona", 
        "respuesta_3": "Sevilla", 
        "respuesta_4": "Valencia", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "facil",
        "pregunta": "¿De qué país es Diego Maradona?",
        "respuesta_1": "Argentina", 
        "respuesta_2": "España", 
        "respuesta_3": "Brasil", 
        "respuesta_4": "Italia", 
        "respuesta_correcta": 1},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿En qué año ganó Argentina su primera Copa del Mundo?",
        "respuesta_1": "1974", 
        "respuesta_2": "1978", 
        "respuesta_3": "1982", 
        "respuesta_4": "1986", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Qué club es conocido como 'Los Diablos Rojos'?",
        "respuesta_1": "Liverpool", 
        "respuesta_2": "Benfica", 
        "respuesta_3": "Manchester United", 
        "respuesta_4": "Bayern Munich", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Cuál es el apodo de la selección italiana?",
        "respuesta_1": "La Roja", 
        "respuesta_2": "La Canarinha", 
        "respuesta_3": "La Albiceleste", 
        "respuesta_4": "La Azzurra", 
        "respuesta_correcta": 4},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿En qué club debutó Lionel Messi profesionalmente?",
        "respuesta_1": "Newell's", 
        "respuesta_2": "Inter Miami", 
        "respuesta_3": "FC Barcelona", 
        "respuesta_4": "PSG", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Qué selección ganó la Copa del Mundo 1998?",
        "respuesta_1": "Brasil", 
        "respuesta_2": "Argentina", 
        "respuesta_3": "Francia", 
        "respuesta_4": "Alemania", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Qué jugador es conocido como 'El Fenómeno'?",
        "respuesta_1": "Zidane", 
        "respuesta_2": "Ronaldo Nazário", 
        "respuesta_3": "Ronaldinho", 
        "respuesta_4": "Kaká", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Qué club ganó la primera edición de la Champions League en 1956?",
        "respuesta_1": "AC Milan", 
        "respuesta_2": "Benfica", 
        "respuesta_3": "Real Madrid", 
        "respuesta_4": "Manchester United", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Cuál seleccion ganó la Copa América 2021?",
        "respuesta_1": "Brasil", 
        "respuesta_2": "Argentina", 
        "respuesta_3": "Uruguay", 
        "respuesta_4": "Chile", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Quién fue el entrenador campeón del mundo con España en 2010?",
        "respuesta_1": "Luis Aragonés", 
        "respuesta_2": "Vicente del Bosque", 
        "respuesta_3": "Pep Guardiola", 
        "respuesta_4": "Luis Enrique", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "media",
        "pregunta": "¿Qué selección ganó la primera Copa del Mundo en 1930?",
        "respuesta_1": "Argentina", 
        "respuesta_2": "Brasil", 
        "respuesta_3": "Italia", 
        "respuesta_4": "Uruguay", 
        "respuesta_correcta": 4},
    {
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿En qué equipo jugaba Maradona cuando ganó el Balón de Oro en 1986?",
        "respuesta_1": "Barcelona", 
        "respuesta_2": "Napoli", 
        "respuesta_3": "Boca Juniors", 
        "respuesta_4": "Sevilla", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Cuál es el único club argentino que ganó la Copa Intercontinental 3 veces?",
        "respuesta_1": "River Plate", 
        "respuesta_2": "Boca Juniors", 
        "respuesta_3": "Independiente", 
        "respuesta_4": "Racing Club", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿En qué año se instauró el uso de tarjetas amarillas y rojas en el fútbol?",
        "respuesta_1": "1966", 
        "respuesta_2": "1970", 
        "respuesta_3": "1974", 
        "respuesta_4": "1982", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Quién fue el primer jugador en superar los 800 goles oficiales en su carrera?",
        "respuesta_1": "Cristiano Ronaldo", 
        "respuesta_2": "Messi", 
        "respuesta_3": "Pelé", 
        "respuesta_4": "Romário", 
        "respuesta_correcta": 1},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Cuál fue el primer club de la historia en ganar el sextete?",
        "respuesta_1": "Bayern Munich", 
        "respuesta_2": "Real Madrid", 
        "respuesta_3": "Barcelona", 
        "respuesta_4": "Inter de Milán", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Quién fue el técnico campeón del mundo con Alemania en 2014?",
        "respuesta_1": "Joachim Löw", 
        "respuesta_2": "Jurgen Klopp", 
        "respuesta_3": "Hansi Flick", 
        "respuesta_4": "Rudi Völler", 
        "respuesta_correcta": 1},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Qué selección quedó subcampeona en el Mundial 1994?",
        "respuesta_1": "Italia", 
        "respuesta_2": "Argentina", 
        "respuesta_3": "Holanda", 
        "respuesta_4": "Alemania", 
        "respuesta_correcta": 1},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Qué jugador ganó el primer Balón de Oro de la historia en 1956?",
        "respuesta_1": "Alfredo Di Stéfano", 
        "respuesta_2": "Stanley Matthews", 
        "respuesta_3": "Raymond Kopa", 
        "respuesta_4": "Eusébio", 
        "respuesta_correcta": 2},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Quién es el máximo goleador histórico de la Champions League?",
        "respuesta_1": "Lionel Messi", 
        "respuesta_2": "Raúl", 
        "respuesta_3": "Cristiano Ronaldo", 
        "respuesta_4": "Benzema", 
        "respuesta_correcta": 3},
    {   
        "categoria": "futbol",
        "dificultad": "dificil",
        "pregunta": "¿Qué club es conocido como 'El Rey de Copas' en Argentina?",
        "respuesta_1": "River Plate", 
        "respuesta_2": "Independiente", 
        "respuesta_3": "San Lorenzo", 
        "respuesta_4": "Vélez", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Cuál es el fontanero más famoso de Nintendo?", 
        "respuesta_1": "Mario", 
        "respuesta_2": "Luigi", 
        "respuesta_3": "Toad", 
        "respuesta_4": "Wario", 
        "respuesta_correcta": 1},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿En qué videojuego aparece el personaje 'Pikachu'?", 
        "respuesta_1": "Zelda", 
        "respuesta_2": "Pokémon", 
        "respuesta_3": "Metroid", 
        "respuesta_4": "Sonic", 
        "respuesta_correcta": 2},
    {
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Qué consola creó Sony?", 
        "respuesta_1": "Xbox", 
        "respuesta_2": "PlayStation", 
        "respuesta_3": "Wii", 
        "respuesta_4": "GameCube", 
        "respuesta_correcta": 2},
    {
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Cuál es el héroe principal de The Legend of Zelda?", 
        "respuesta_1": "Zelda", 
        "respuesta_2": "Link", 
        "respuesta_3": "Ganon",
        "respuesta_4": "Sheik", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Qué personaje dice '¡Here we go!'?", 
        "respuesta_1": "Luigi", 
        "respuesta_2": "Sonic", 
        "respuesta_3": "Mario", 
        "respuesta_4": "Crash", 
        "respuesta_correcta": 3},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Qué tipo de juego es FIFA?", 
        "respuesta_1": "Carreras", 
        "respuesta_2": "Deportes", 
        "respuesta_3": "Aventura", 
        "respuesta_4": "Plataformas", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Cuál es el enemigo principal de Sonic?", 
        "respuesta_1": "Bowser", 
        "respuesta_2": "Eggman", 
        "respuesta_3": "Shadow", 
        "respuesta_4": "Metal Sonic", 
        "respuesta_correcta": 2},
    {
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Qué empresa creó la saga Halo?", 
        "respuesta_1": "Valve", 
        "respuesta_2": "Bungie", 
        "respuesta_3": "EA", 
        "respuesta_4": "Ubisoft", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Qué famoso juego tiene piezas llamadas ‘tetriminos’?", 
        "respuesta_1": "Pac-Man", 
        "respuesta_2": "Tetris", 
        "respuesta_3": "Space Invaders", 
        "respuesta_4": "Snake", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "facil",
        "pregunta": "¿Cuál es el personaje principal de Minecraft?", 
        "respuesta_1": "Steve", 
        "respuesta_2": "Bob", 
        "respuesta_3": "Jack", 
        "respuesta_4": "Alex", 
        "respuesta_correcta": 1},
    {
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿En qué juego aparece la ciudad de Raccoon City?", 
        "respuesta_1": "Silent Hill", 
        "respuesta_2": "Resident Evil", 
        "respuesta_3": "Dino Crisis", 
        "respuesta_4": "Dead Rising", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Cuál es el nombre completo de 'Master Chief'?", 
        "respuesta_1": "John-117", 
        "respuesta_2": "Marcus Fenix", 
        "respuesta_3": "Jack Cooper", 
        "respuesta_4": "Shepard-001", 
        "respuesta_correcta": 1},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Qué arma es la más icónica de Cloud en Final Fantasy VII?", 
        "respuesta_1": "Gunblade", 
        "respuesta_2": "Buster Sword", 
        "respuesta_3": "Masamune", 
        "respuesta_4": "Dragon Lance", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Cuál es el planeta natal de Samus Aran?", 
        "respuesta_1": "Zebes", 
        "respuesta_2": "SR388", 
        "respuesta_3": "K-2L", 
        "respuesta_4": "Talos I", 
        "respuesta_correcta": 3},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Cómo se llama el villano principal de Far Cry 3?", 
        "respuesta_1": "Vaas Montenegro", 
        "respuesta_2": "Pagan Min", 
        "respuesta_3": "Joseph Seed", 
        "respuesta_4": "Micah Bell", 
        "respuesta_correcta": 1},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Qué compañía desarrolló The Witcher 3?", 
        "respuesta_1": "BioWare", 
        "respuesta_2": "CD Projekt Red", 
        "respuesta_3": "Square Enix", 
        "respuesta_4": "Obsidian", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿En qué año se lanzó el primer PlayStation?", 
        "respuesta_1": "1992", 
        "respuesta_2": "1994", 
        "respuesta_3": "1996", 
        "respuesta_4": "1998", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Cómo se llama el protagonista de Red Dead Redemption 2?", 
        "respuesta_1": "John Marston", 
        "respuesta_2": "Arthur Morgan", 
        "respuesta_3": "Dutch van der Linde", 
        "respuesta_4": "Bill Williamson", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Qué juego popularizó el género Battle Royale?", 
        "respuesta_1": "H1Z1", 
        "respuesta_2": "PUBG", 
        "respuesta_3": "Fortnite", 
        "respuesta_4": "Apex Legends", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "media",
        "pregunta": "¿Cuál es el nombre del mítico dragón final de Skyrim?", 
        "respuesta_1": "Alduin", 
        "respuesta_2": "Parthurnaax", 
        "respuesta_3": "Mirmulnir", 
        "respuesta_4": "Vahlok", 
        "respuesta_correcta": 1},
    {
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Cómo se llama el creador original de la saga Metal Gear?", 
        "respuesta_1": "Shigeru Miyamoto", 
        "respuesta_2": "Hideo Kojima", 
        "respuesta_3": "Yoko Taro", 
        "respuesta_4": "Tetsuya Nomura", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "En Dark Souls, ¿qué objeto se usa para encender hogueras y subir de nivel?", 
        "respuesta_1": "Humanity", 
        "respuesta_2": "Estus Shard", 
        "respuesta_3": "Soul Vessel", 
        "respuesta_4": "Fire Gem", 
        "respuesta_correcta": 1},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Cuál fue el primer juego en usar el término 'Metroidvania'?", 
        "respuesta_1": "Castlevania", 
        "respuesta_2": "Metroid", 
        "respuesta_3": "Super Metroid", 
        "respuesta_4": "Symphony of the Night", 
        "respuesta_correcta": 4},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Cómo se llama la inteligencia artificial enemiga en System Shock?", 
        "respuesta_1": "GLADOS", 
        "respuesta_2": "SHODAN", 
        "respuesta_3": "Mother Brain", 
        "respuesta_4": "Karen", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Qué juego fue desarrollado completamente por una sola persona y se volvió un éxito mundial?", "respuesta_1": "Undertale", 
        "respuesta_2": "Stardew Valley", 
        "respuesta_3": "Papers, Please", 
        "respuesta_4": "Minecraft", 
        "respuesta_correcta": 4},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Cuál es el nombre del planeta en el que ocurre Mass Effect 1 al comenzar el juego?", "respuesta_1": "Eden Prime",
        "respuesta_2": "Terra Nova", 
        "respuesta_3": "Noveria", 
        "respuesta_4": "Ilos", 
        "respuesta_correcta": 1},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "En Bloodborne, ¿cómo se llama la ciudad principal?", 
        "respuesta_1": "Iosefka", 
        "respuesta_2": "Cainhurst", 
        "respuesta_3": "Yharnam", 
        "respuesta_4": "Hemwick", 
        "respuesta_correcta": 3},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Qué juego introdujo el personaje 'Ciri'?", 
        "respuesta_1": "The Witcher 1", 
        "respuesta_2": "The Witcher 2", 
        "respuesta_3": "The Witcher 3", 
        "respuesta_4": "Gwent", 
        "respuesta_correcta": 1},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "¿Cuál fue el primer videojuego de la historia según registros oficiales?", 
        "respuesta_1": "Pong", 
        "respuesta_2": "Spacewar!", 
        "respuesta_3": "Tennis for Two", 
        "respuesta_4": "Computer Space", 
        "respuesta_correcta": 2},
    {   
        "categoria": "JUEGOS",
        "dificultad": "dificil",
        "pregunta": "En la saga Kingdom Hearts, ¿cómo se llama la llave-espada principal?", 
        "respuesta_1": "Oblivion", 
        "respuesta_2": "Kingdom Key", 
        "respuesta_3": "Ultima Weapon", 
        "respuesta_4": "Oathkeeper", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Quién fue el primer emperador romano?",
        "respuesta_1": "Julio César", 
        "respuesta_2": "Augusto", 
        "respuesta_3": "Nerón", 
        "respuesta_4": "Trajano", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿En qué año comenzó la Primera Guerra Mundial?",
        "respuesta_1": "1914", 
        "respuesta_2": "1918", 
        "respuesta_3": "1939", 
        "respuesta_4": "1945", 
        "respuesta_correcta": 1},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Quién descubrió América en 1492?",
        "respuesta_1": "Cristóbal Colón", 
        "respuesta_2": "Américo Vespucio", 
        "respuesta_3": "Hernán Cortés", 
        "respuesta_4": "Marco Polo", 
        "respuesta_correcta": 1},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Cuál de estos países fue potencia del Eje en la Segunda Guerra Mundial?",
        "respuesta_1": "Alemania", 
        "respuesta_2": "Francia", 
        "respuesta_3": "Reino Unido", 
        "respuesta_4": "Canadá", 
        "respuesta_correcta": 1},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Qué gran muralla se encuentra en Asia?",
        "respuesta_1": "Muralla Romana", 
        "respuesta_2": "Muralla de China", 
        "respuesta_3": "Muralla Azteca", 
        "respuesta_4": "Muralla de India", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Qué civilización construyó las pirámides de Giza?",
        "respuesta_1": "Romanos", 
        "respuesta_2": "Mayas", 
        "respuesta_3": "Egipcios", 
        "respuesta_4": "Persas", 
        "respuesta_correcta": 3},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿En qué década llegó el hombre a la Luna?",
        "respuesta_1": "1950", 
        "respuesta_2": "1960", 
        "respuesta_3": "1970", 
        "respuesta_4": "1980", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Qué imperio gobernó Gengis Khan?",
        "respuesta_1": "Imperio Romano", 
        "respuesta_2": "Imperio Mongol", 
        "respuesta_3": "Imperio Otomano", 
        "respuesta_4": "Imperio Persa", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿En qué continente se desarrolló la Primera Guerra Mundial principalmente?",
        "respuesta_1": "Asia", 
        "respuesta_2": "Europa", 
        "respuesta_3": "África", 
        "respuesta_4": "Oceanía", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "facil",
        "pregunta": "¿Cuál fue la capital del Imperio Romano?",
        "respuesta_1": "Atenas", 
        "respuesta_2": "Roma", 
        "respuesta_3": "Alejandría", 
        "respuesta_4": "Florencia", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Qué tratado puso fin a la Primera Guerra Mundial?", 
        "respuesta_1": "Tratado de Roma", 
        "respuesta_2": "Tratado de París", 
        "respuesta_3": "Tratado de Versalles", 
        "respuesta_4": "Tratado de Londres", 
        "respuesta_correcta": 3},
    {
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿En qué año cayó el Muro de Berlín?", 
        "respuesta_1": "1989", 
        "respuesta_2": "1991", 
        "respuesta_3": "1985", 
        "respuesta_4": "1993", 
        "respuesta_correcta": 1},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Qué civilización utilizó la escritura cuneiforme?", 
        "respuesta_1": "Mesopotamia", 
        "respuesta_2": "Grecia", 
        "respuesta_3": "Roma", 
        "respuesta_4": "Egipto", 
        "respuesta_correcta": 1},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Qué país lideró la colonización de América del Sur?", 
        "respuesta_1": "Francia", 
        "respuesta_2": "Portugal", 
        "respuesta_3": "España", 
        "respuesta_4": "Alemania", 
        "respuesta_correcta": 3},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Cómo se llamaba el líder soviético durante la Segunda Guerra Mundial?", 
        "respuesta_1": "Lenin", 
        "respuesta_2": "Stalin", 
        "respuesta_3": "Gorbachev", 
        "respuesta_4": "Trotsky", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Qué guerra enfrentó a Estados Unidos y la URSS indirectamente?", 
        "respuesta_1": "Guerra Civil Española", 
        "respuesta_2": "Guerra Fría", 
        "respuesta_3": "Guerra de Corea", 
        "respuesta_4": "Guerra de Vietnam",
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Cuál fue la principal ruta comercial entre Asia y Europa?", 
        "respuesta_1": "La Ruta de la Seda",  
        "respuesta_2": "La Ruta Imperial", 
        "respuesta_3": "El Camino del Inca", 
        "respuesta_4": "La Ruta Oriental",
        "respuesta_correcta": 1},
    {
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Qué líder militar cruzó los Alpes en elefantes?", 
        "respuesta_1": "Alejandro Magno", 
        "respuesta_2": "César", 
        "respuesta_3": "Aníbal", 
        "respuesta_4": "Atila", 
        "respuesta_correcta": 3},
    {   
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿Qué evento inició la Revolución Francesa?", 
        "respuesta_1": "La toma de la Bastilla", 
        "respuesta_2": "La ejecución del rey", 
        "respuesta_3": "La declaración de independencia", 
        "respuesta_4": "La guerra contra Inglaterra", 
        "respuesta_correcta": 1},
    {       
        "categoria": "historia",
        "dificultad": "media",
        "pregunta": "¿En qué guerra luchó Napoleón Bonaparte?", 
        "respuesta_1": "Guerras Napoleónicas", 
        "respuesta_2": "Guerra de Crimea", 
        "respuesta_3": "Guerra Franco-Prusiana", 
        "respuesta_4": "Guerra Mundial", 
        "respuesta_correcta": 1},
    {
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿En qué año comenzó la Edad Media tras la caída del Imperio Romano de Occidente?", 
        "respuesta_1": "395", 
        "respuesta_2": "410", 
        "respuesta_3": "476", 
        "respuesta_4": "509", 
        "respuesta_correcta": 3},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Qué ciudad fue capital del Imperio Bizantino?", 
        "respuesta_1": "Alejandría", 
        "respuesta_2": "Constantinopla", 
        "respuesta_3": "Antioquía", 
        "respuesta_4": "Roma", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Qué gran emperador fundó el Imperio Acadio?", 
        "respuesta_1": "Sargón", 
        "respuesta_2": "Hammurabi", 
        "respuesta_3": "Nabucodonosor", 
        "respuesta_4": "Darío", 
        "respuesta_correcta": 1},
    {
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Cuál de estos filósofos fue tutor de Alejandro Magno?", 
        "respuesta_1": "Platón", 
        "respuesta_2": "Sócrates", 
        "respuesta_3": "Aristóteles", 
        "respuesta_4": "Demócrito", 
        "respuesta_correcta": 3},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Cuál fue la causa inmediata del inicio de la Primera Guerra Mundial?", 
        "respuesta_1": "La invasión de Polonia", 
        "respuesta_2": "El asesinato del archiduque Francisco Fernando", 
        "respuesta_3": "La caída del zar ruso", 
        "respuesta_4": "La firma del Tratado de Versalles", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Qué líder militar cartaginés venció a Roma en la Batalla de Cannas?", 
        "respuesta_1": "Escipión", 
        "respuesta_2": "Aníbal", 
        "respuesta_3": "Atila", 
        "respuesta_4": "Darío", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Qué tratado dividió el mundo entre España y Portugal en 1494?", 
        "respuesta_1": "Tratado de París", 
        "respuesta_2": "Tratado de Berlín", 
        "respuesta_3": "Tratado de Tordesillas", 
        "respuesta_4": "Tratado de Lisboa",
        "respuesta_correcta": 3},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Quién fue el primer emperador de la dinastía Qin en China?", 
        "respuesta_1": "Qin Shi Huang", 
        "respuesta_2": "Liu Bang", 
        "respuesta_3": "Sun Tzu", 
        "respuesta_4": "Wu Zetian", 
        "respuesta_correcta": 1},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿En qué año terminó oficialmente la Guerra Fría?", 
        "respuesta_1": "1989", 
        "respuesta_2": "1991", 
        "respuesta_3": "1993", 
        "respuesta_4": "1995", 
        "respuesta_correcta": 2},
    {   
        "categoria": "historia",
        "dificultad": "dificil",
        "pregunta": "¿Qué cultura mesoamericana construyó la ciudad de Teotihuacán?", 
        "respuesta_1": "Azteca", 
        "respuesta_2": "Olmeca", 
        "respuesta_3": "Maya", 
        "respuesta_4": "Desconocida", 
        "respuesta_correcta": 4}    
]